services:
  db:
    build: ./db
    ports:
      - 3306:3306 # host:container
    env_file:
      - ./db/.env
    volumes:
      # DB 上のデータの実体については named volume を使う
      # 開発用ディレクトリにマウントしないことで、rm -rf の事故を防ぐ
      - mysql-data:/var/lib/mysql
      - ./db/initdb:/docker-entrypoint-initdb.d

volumes:
  mysql-data: ~ # use default settings
